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

### 넘파이 ndarray 개요

In [4]:
import numpy as np

In [5]:
array1 = np.array([1, 2, 3])
print('array1 type: ', type(array1))
print('array1 array 형태: ', array1.shape)

array2 = np.array([[1, 2, 3], [2, 3, 4]])
print('array2 type: ', type(array2))
print('array2 array 형태: ', array2.shape)

array3 = np.array([[1, 2, 3]])
print('array3 type: ', type(array3))
print('array3 array 형태: ', array3.shape)

array1 type:  <class 'numpy.ndarray'>
array1 array 형태:  (3,)
array2 type:  <class 'numpy.ndarray'>
array2 array 형태:  (2, 3)
array3 type:  <class 'numpy.ndarray'>
array3 array 형태:  (1, 3)


In [6]:
print('array1: {0}차원, array2: {1}차원, array3: {2}차원'.format(array1.ndim, array2.ndim, array3.ndim))

array1: 1차원, array2: 2차원, array3: 2차원


머신러닝 알고리즘 데이터 세트 간 입출력 변환 수행하다보면 1차원 또는 다차원 요구하는 경우가 있음<br>이때 데이터값은 동일하나 차원이 달라 오류 빈번히 발생하므로 명확히 알아야 함

<hr>

### ndarray의 데이터 타입

ndarray 내의 데이터 타입은 연산 특성상 같은 데이터 타입만 가능

In [9]:
list1 = [1, 2, 3]
print(type(list1))
array1 = np.array(list1)
print(type(array1))
print(array1, array1.dtype) # dtyep: ndarray 내의 데이터 타입

<class 'list'>
<class 'numpy.ndarray'>
[1 2 3] int64


서로 다른 데이터 유형이 섞여있는 리스트를 ndarray 변환시 데이터 크기가 더 큰 타입으로 일괄 적용

In [11]:
list2 = [1, 2, 'test']
array2 = np.array(list2)
print(array2, array2.dtype)

list3 = [1, 2, 3.0]
array3 = np.array(list3)
print(array3, array3.dtype)

['1' '2' 'test'] <U21
[1. 2. 3.] float64


int32 -> float64 -> int32 변환: 소수점 이하는 없어질 것임

In [13]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float, array_float.dtype)

array_int1 = array_float.astype('int32')
print(array_int1, array_int1.dtype)

array_float1 = np.array([1.1, 2.1, 3.1])
array_int2 = array_float1.astype('int32')
print(array_int2, array_int2.dtype)

[1. 2. 3.] float64
[1 2 3] int32
[1 2 3] int32


<hr>

### ndarray를 편리하게 생성하기 - arange, zeors, ones

특정 크기와 차원을 가진 ndarray를 연속값이나 0 또는 1로 초기화해 쉽게 생성하는 법(arange(), zeros(), ones())

In [14]:
sequence_array = np.arange(10)
print(sequence_array)
print(sequence_array.dtype, sequence_array.shape)

[0 1 2 3 4 5 6 7 8 9]
int64 (10,)


zeros(), ones()는 모든 값을 0 또는 1로 채운 ndarray를 반환, dtype 지정하지 않으면 float64 형으로 채움

In [16]:
zero_array = np.zeros((3, 2), dtype='int32')
print(zero_array)
print(zero_array.dtype, zero_array.shape)

one_array = np.ones((3, 2))
print(one_array)
print(one_array.dtype, one_array.shape)

[[0 0]
 [0 0]
 [0 0]]
int32 (3, 2)
[[1. 1.]
 [1. 1.]
 [1. 1.]]
float64 (3, 2)


<hr>

### ndarray의 차원과 크기를 변경하는 reshape()

In [17]:
array1 = np.arange(10)
print('array1: \n', array1)

array2 = array1.reshape(2, 5)
print('array2: \n', array2)

array3 = array1.reshape(5, 2)
print('array3: \n', array3)

array1: 
 [0 1 2 3 4 5 6 7 8 9]
array2: 
 [[0 1 2 3 4]
 [5 6 7 8 9]]
array3: 
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


단, 지정된 사이즈로의 변경이 불가능하면 오류 발생 -> (10,) 데이터를 (4, 3)으로 reshape 불가

In [18]:
# array1.reshape(4, 3)

인자로 -1을 적용하면 효율적 사용 가능, 고정된 인자에 맞게 자동 변환 역할

In [20]:
array1 = np.arange(10)
print(array1)
array2 = array1.reshape(-1, 5) # column을 5로 고정
print('array2 shape: ', array2.shape)
array3 = array1.reshape(5, -1) # row를 5로 고정
print('array3 shape: ', array3.shape)

[0 1 2 3 4 5 6 7 8 9]
array2 shape:  (2, 5)
array3 shape:  (5, 2)


-1을 사용하더라도 호환될 수 없는 형태는 오류 발생 -> (10,) 데이터를 (-1, 4)으로 불가

In [21]:
# array1.reshape(-1, 4)

-1 인자는 reshape(-1, 1)과 같은 형태로 자주 사용됨<br> 이는 원본 ndarray가 어떤 형태라도 2차원이고, 여러 개의 row를 가지되 반드시 1개의 칼럼을 가진 ndarray로 변환됨을 보장<br> stack이나 concat으로 결합할 때 형태 통일에 유용함

In [23]:
array1 = np.arange(8)
array3d = array1.reshape((2, 2, 2))
print('array3d: \n', array3.tolist())

# 3차원 ndarray를 2차원 ndarray로 변환
array5 = array3d.reshape(-1, 1)
print('array5: \n', array5.tolist())
print('array5 shape: ', array5.shape)

# 1차원 ndarray를 2차원 ndarray로 변환
array6 = array1.reshape(-1, 1)
print('array6: \n', array6.tolist())
print('array6 shape: ', array6.shape)

array3d: 
 [[0, 1], [2, 3], [4, 5], [6, 7], [8, 9]]
array5: 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array5 shape:  (8, 1)
array6: 
 [[0], [1], [2], [3], [4], [5], [6], [7]]
array6 shape:  (8, 1)


<hr>

### 넘파이의 ndarray의 데이터 세트 선택하기 - 인덱싱(Indexing)

ndarray 내의 일부 데이터 세트 or 특정 데이터만 선택

1. 특정한 데이터만 추출: 원하는 위치의 인덱스 값 지정
2. 슬라이싱(Slicing): 연속된 인덱스 상 ndarray 추출(ex) 1:5 -> 1부터 4까지
3. 팬시 인덱싱(Fancy Indexing): 일정한 인덱싱 집합을 리스트 또는 ndarray 형태로 지정해 해당 위치에 있는 데이터의 ndarray를 반환
4. 불린 인덱싱(Boolean Indexing): 특정 조건에 해당하는지 여부인 True/False 값 인덱싱 집합을 기반으로 True에 해당하는 인덱스 위치에 있는 데이터의 ndarray를 반환

##### 단일 값 추출

In [25]:
# 1부터 9까지의 1차원 ndarray 생성
array1 = np.arange(start=1, stop=10)
print('array1: ', array1)

# index는 0부터 시작하므로 array1[2]는 3번째 index 위치의 데이터 값 의미
value = array1[2]
print('value: ', value)
print(type(value))

array1:  [1 2 3 4 5 6 7 8 9]
value:  3
<class 'numpy.int64'>


In [31]:
print('맨 뒤의 값:', array1[-1], '맨 뒤에서 두 번째 값:', array1[-2])

맨 뒤의 값: 9 맨 뒤에서 두 번째 값: 8


In [32]:
array1[0] = 9
array1[8] = 0
print('array1:', array1)

array1: [9 2 3 4 5 6 7 8 0]


In [34]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print(array2d)

print('(row=0, col=0) index 가리키는 값:', array2d[0, 0])
print('(row=0, col=1) index 가리키는 값:', array2d[0, 1])
print('(row=1, col=0) index 가리키는 값:', array2d[1, 0])
print('(row=2, col=2) index 가리키는 값:', array2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(row=0, col=0) index 가리키는 값: 1
(row=0, col=1) index 가리키는 값: 2
(row=1, col=0) index 가리키는 값: 4
(row=2, col=2) index 가리키는 값: 9


넘파이의 다차원 ndarray는 row, column이 아닌 axis 구분을 가짐 <br>
2차원에서는, axis 0이 row 축, axis 1이 column 축 의미<br>
생략시 axis 0을 의미

##### 슬라이싱

':' 기호를 사용해 연속 데이터 슬라이싱해서 추출

In [35]:
array1 = np.arange(start=1, stop=10)
array3 = array1[0:3]
print(array3)
print(type(array3))

[1 2 3]
<class 'numpy.ndarray'>


시작 종료 생략 가능

In [36]:
array1 = np.arange(start=1, stop=10)
array4 = array1[:3]
print(array4)

array5 = array1[3:]
print(array5)

array6 = array1[:]
print(array6)

[1 2 3]
[4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


2차원 ndarray 슬라이싱

In [39]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)
print('array2:\n', array2d)

print('array2d[0:2, 0:2] \n', array2d[0:2, 0:2])
print('array2d[1:3, 0:3] \n', array2d[1:3, 0:3])
print('array2d[1:3, :] \n', array2d[1:3, :])
print('array2d[:, :] \n', array2d[:, :])
print('array2d[:2, 1:] \n', array2d[:2, 1:])
print('array2d[:2, 0] \n', array2d[:2, 0])

array2:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[0:2, 0:2] 
 [[1 2]
 [4 5]]
array2d[1:3, 0:3] 
 [[4 5 6]
 [7 8 9]]
array2d[1:3, :] 
 [[4 5 6]
 [7 8 9]]
array2d[:, :] 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
array2d[:2, 1:] 
 [[2 3]
 [5 6]]
array2d[:2, 0] 
 [1 4]


array2d[:2, 0]과 같이 한 축에는 슬라이싱, 다른 축에는 단일 값 인덱스 가능 <br>
2차원 ndarray에서 뒤에 오는 인덱스를 없애면 1차원 ndarray 반환

In [41]:
print(array2d[0])
print(array2d[1])
print('array2d[0] shape:', array2d[0].shape, 'array2d[1] shape:', array2d[1].shape)

[1 2 3]
[4 5 6]
array2d[0] shape: (3,) array2d[1] shape: (3,)


##### 팬시 인덱싱

인덱스 집합 지정하여 해당 위치 인덱스에 해당하는 ndarray 반환하는 방식

In [44]:
array1d = np.arange(start=1, stop=10)
array2d = array1d.reshape(3, 3)

array3 = array2d[[0, 1], 2]
print('array2d[[0, 1], 2] =>', array3.tolist())

array4 = array2d[[0, 1], 0:2]
print('array2d[[0, 1], 0:2] =>', array4.tolist())

array5 = array2d[[0, 1]]
print('array2d[[0, 1]] =>', array5.tolist())

array2d[[0, 1], 2] => [3, 6]
array2d[[0, 1], 0:2] => [[1, 2], [4, 5]]
array2d[[0, 1]] => [[1, 2, 3], [4, 5, 6]]


##### 불린 인덱싱

[] 내에 조건문을 그대로 기재

In [45]:
array1d = np.arange(start=1, stop=10)
# [] 안에 array1d > 5 Boolean indexing 적용
array3 = array1d[array1d > 5]
print('array1d > 5 불린 인덱싱 결과 값:', array3)

array1d > 5 불린 인덱싱 결과 값: [6 7 8 9]


In [46]:
array1d > 5

array([False, False, False, False, False,  True,  True,  True,  True])

위와 동일한 불린 ndarray를 만들고 이를 array1d[] 내에 인덱스로 입력해도 동일한 반환

In [47]:
boolean_indexes = np.array([False, False, False, False, False,  True,  True,  True,  True])
array3 = array1d[boolean_indexes]
print('불린 인덱스로 필터링 결과:', array3)

불린 인덱스로 필터링 결과: [6 7 8 9]


In [48]:
indexes = np.array([5, 6, 7, 8])
array4 = array1d[indexes]
print('일반 인덱스로 필터링 결과:', array4)

일반 인덱스로 필터링 결과: [6 7 8 9]


불린 인덱싱 동작 단계<br> 
Step 1: 필터링 조건을 [] 안에 기재<br> 
Step 2: True 해당 인덱스 값만 저장(True 값 자체가 아닌 해당 인덱스임)<br> 
Step 3: 저장된 인덱스 데이터 세트로 ndarray 조회

### 행렬의 정렬 - sort()와 argsort()